version: '3'
services:
  database:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: 767kjHU#tzRq12
    ports:
      - "1433:1433"
  db-init:
    image: mcr.microsoft.com/mssql/server:2019-latest
    network_mode: service:database
    command: bash -c 'until /opt/mssql-tools/bin/sqlcmd -U sa -P 767kjHU#tzRq12 -Q "CREATE DATABASE demodb"; do echo retry && sleep 1; done'
    depends_on:
      - database