version: '3'
services:
  database:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "mssqlpw"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql
volumes:
  my-volume: