version: '3'
services:
  database:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: 767kjHU#tzRq12
    ports:
      - "1433:1433"